/* Bar functionality */
#include "bar_indicators.c"
#include "bar_tagicons.c"

#include "bar_ltsymbol.c"
#include "bar_status2d.c"
#include "bar_tags.c"
#include "bar_wintitle.c"
#include "bar_systray.c"

/* Other patches */
#include "attachx.c"
#include "cfacts.c"
#include "cyclelayouts.c"
#include "dragcfact.c"
#include "movestack.c"
#include "pertag.c"
#include "rotatestack.c"
#include "scratchpad.c"
#include "selfrestart.c"
#include "setborderpx.c"
#include "vanitygaps.c"
#include "warp.c"
#include "xrdb.c"
#include "dragmfact.c"
/* Layouts */
#include "layout_facts.c"
#include "layout_bstack.c"
#include "layout_centeredmaster.c"
#include "layout_deck.c"
#include "layout_flextile-deluxe.c"
#include "layout_grid.c"
#include "layout_monocle.c"
#include "layout_tile.c"

