#!/bin/bash

setxkbmap se
xsetroot -cursor_name left_ptr &
/home/martin/.screenlayout/dual.sh &
/usr/lib/polkit-gnome//polkit-gnome-authentication-agent-1 &

#ckb-next --background &
signal-desktop --start-in-tray &
nitrogen --restore &
#variety &
flameshot &
pamac-tray &
#picom -Cf &
#dunst &
numlockx &
#dwmblocks &
#xmobar &
#nm-applet &

exec xmonad
